TARGET=loop_and_helix_1jump_NOT_cross_ax.dat

all:$(TARGET)

loop_and_helix_1jump_NOT_cross_ax.dat: ~/proana_pro_rep/1jump_NOT_cross_ax.nishi ~/bin/length_loop_helix
	~/bin/length_loop_helix ~/proana_pro_rep/1jump_NOT_cross_ax.nishi >loop_and_helix_1jump_NOT_cross_ax.dat
